### ISSUE TITLE
Syntax error in translation file

### ISSUE THREAD

**Issue by buttflattery** [kop/yii2-scroll-pager#107]
Hello a recent update caused this bug 

> ParseError: syntax error, unexpected ''Load previous items'' (T_CONSTANT_ENCAPSED_STRING), expecting ']' in /vendor/kop/yii2-scroll-pager/messages/en/general.php:6

which is because of a missing comma `,` after the second key=>value pair declared in the mentioned file

```
return [
    'Load more items' => 'Load more items',
    'You reached the end' => 'You reached the end'
    'Load previous items' => 'Load previous items'
];

```

**Comment by onmotion** [comment]
Hi.
Fixed in #106 
Please try to update
