### ISSUE TITLE
Is it possible to show or hide spinner manually?

### ISSUE THREAD

**Issue by alexweb-zz** [kop/yii2-scroll-pager#17]
I'm using Spinner extension. It shows spinner when data is loading and removes it after data is loaded. 
But is it possible to manually call show() or hide() spinner?  
(I use it with Masonry and Imagesloaded and want to hide spinner when images are loaded, not when data is received)

**Comment by con322** [comment]
I am trying to implement this with masonry however I am having trouble loading new items and then getting the masonry to execute again, any chance you could help?
