### ISSUE TITLE
Undefined variable: dataProvider

### ISSUE THREAD

**Issue by derah04** [kop/yii2-scroll-pager#24]
whats wrong ?
I found this error ..
(Undefined variable: dataProvider )

**Comment by n1k88** [comment]
It is not an error from extension. You need data for display from controller. http://www.yiiframework.com/doc-2.0/yii-data-activedataprovider.html

**Comment by kop** [comment]
@derah04, data you provided is not enough for understanding of your problem. Please add more details about the error. Thank you.

**Comment by derah04** [comment]
Im say sorry before, I dont understand to use this extention ..
Can you see me the example web or web file that use this extention ?

Thank you
