### ISSUE TITLE
IAS Events are not working

### ISSUE THREAD

**Issue by usualdesigner** [kop/yii2-scroll-pager#30]
Looks like events doesn't works if they were defined in the pagination widget. https://github.com/kop/yii2-scroll-pager/blob/master/ScrollPager.php#L320

**Comment by kop** [comment]
Link you gave is a declaration of event dependencies (some events are from the extensions), however you are right, events are broken.

My assumption is that the [problem is here](https://github.com/kop/yii2-scroll-pager/blob/2.2.4/ScrollPager.php#L406).

I don't know maybe it was me reading the IAS docs wrong, or events API changed, but currently events are registered with:

```php
// Register event
$this->view->registerJs(
    "jQuery.ias().on('{$name}', {$this->$eventName});",
    View::POS_READY,
    "{$this->id}_ias_{$name}"
);
```

While according to the current IAS documentation it should be:

```php
// Register event
$this->view->registerJs(
    "{$this->id}_ias.on('{$name}', {$this->$eventName});",
    View::POS_READY,
    "{$this->id}_ias_{$name}"
);
```

Right now I don't have any Yii2 (or even PHP) project and time, so testing my theory is pretty much complicated for me. However, if someone could test that proposed fix is working and make a PR, I think a lot of people would be grateful.

**Comment by sni10** [comment]
Фиксили фиксили а ни нихера не пофиксили. Молодцы!
