### ISSUE TITLE
Is it possible to remove ?page=2&per-page=10 from URL?

### ISSUE THREAD

**Issue by con322** [kop/yii2-scroll-pager#32]
Is it possible to remove the page number and per page option from URL?

As it seems to be conflicting with my ajax (alternatively how should I change my ajax)

    $(document).ready(function() {
    $('a.btnsolid-sm').click(function() {
        var Id = jQuery(this).attr('id');
        $.ajax({
            type: 'POST',
            data: {
                'modal_id' : Id,
            },
            url : 'http://localhost:8888/blog/viewmodal?id='+Id,
            success: function(response) {
                if(response) {
                    $('.modal_blog_wrapper').html(response);
                    $('#modal_'+Id).modal('show');
                    $(document).on('hidden.bs.modal', modal_id, function (event) {
                        $(this).remove();
                    });
                } else {
                    alert('Error');
                }
            }
        });

    });

    });

**Comment by usualdesigner** [comment]
Just disable EXTENSION_HISTORY

**Comment by kop** [comment]
It seems like question is answered. Thanks @usualdesigner.

**Comment by gomonkey** [comment]
how to disable EXTENSION_HISTORY ?
