### ISSUE TITLE
eventOnLoaded throws js error when loading newer content

### ISSUE THREAD

**Issue by abdelhady** [kop/yii2-scroll-pager#34]
I'm trying to use `eventOnLoaded` to register a javascript function to be run after loading new content from server, I'm using it like this:
```php
'eventOnLoaded' => new JsExpression("renderStars()")
```
where `renderStars()` is a javascript function to render rating stars, it works fine with refreshing the page which loads the initial content, but when scrolling down to load more content, it throws this javascript error:
> Uncaught TypeError: Cannot read property 'apply' of undefined

in `callbacks.js:31`, I've also tried other events like `eventOnRendered` but got the same result

So, how could I use a JsExpression after loading newer content?

**Comment by spiner** [comment]
Me too. :( "Uncaught TypeError: Cannot read property 'apply' of undefined" after new items are loaded.

**Comment by kop** [comment]
See this issue for a proposed solution https://github.com/kop/yii2-scroll-pager/issues/30.
