### ISSUE TITLE
Uncaught TypeError: jQuery.ias is not a function

### ISSUE THREAD

**Issue by xiaomalover** [kop/yii2-scroll-pager#37]
Uncaught TypeError: jQuery.ias is not a function ?  why?

**Comment by riyaskp** [comment]
I am getting the same error.Could you find the solution?

**Comment by yinhedot** [comment]
refer to : [https://stackoverflow.com/questions/23779374/jquery-ias-infinite-scrolling-packery-iascallbacks-is-not-defined](https://stackoverflow.com/questions/23779374/jquery-ias-infinite-scrolling-packery-iascallbacks-is-not-defined)

js file :  <https://raw.githubusercontent.com/webcreate/infinite-ajax-scroll/2.x/src/callbacks.js>
