### ISSUE TITLE
Scroll down then hit refresh. Page stays on ?page=4&per-page=5

### ISSUE THREAD

**Issue by nsanden** [kop/yii2-scroll-pager#45]

**Comment by masiha68** [comment]
hi ... i have this isuue ... how i can fixed

**Comment by nibinpaul** [comment]
i have same problem.

**Comment by masiha68** [comment]
remove history extension

   public $enabledExtensions = [
        self::EXTENSION_TRIGGER,
        self::EXTENSION_SPINNER,
        self::EXTENSION_NONE_LEFT,
        self::EXTENSION_PAGING,
       // self::EXTENSION_HISTORY
    ];

**Comment by nibinpaul** [comment]
Thank you @masiha68 .
it works.

**Comment by kop** [comment]
This is duplicate of #40.

**Comment by bilginnet** [comment]
I need to changing address bar after scroll. 
if i disabled HISTORY address bar does not changing. 
if i enabled HISTORY address bar changing but previos data does not showing.
How can i fix this ?
