### ISSUE TITLE
Reverse Infinite Scroll Feature

### ISSUE THREAD

**Issue by IvoPereira** [kop/yii2-scroll-pager#48]
Hello,

Do you have anything planned for such a feature?

Something like replicating the Facebook Messages system. Basically, instead of triggering the event on scrolling down, it would trigger it on scrolling up.

Thanks

**Comment by kop** [comment]
@IvoPereira, this question is not to me. This package is based on https://github.com/webcreate/infinite-ajax-scroll, so it supports only features that are present in this plugin :)
