### ISSUE TITLE
How to change action to rquest data?

### ISSUE THREAD

**Issue by sazonov-dev** [kop/yii2-scroll-pager#57]
Hi, how i can change action to request data? 
For example: 
Widget showing on /category/view, but i'm need to get data from /category/products action. When i'm update widget from ajax - firs page loaded from /category/products, but on scroll gets products prom /category/view =(

RU: Написал на английском как смог. На всякий случай пишу на русском: как подменить экшн? Изначально виджет появляется на /category/view, но в дальнейшем я его хочу обновлять по ajax и грузить модели уже с другого экшна /category/products. Когда я обновляюсь по аяксу, первая страница грузится как нужно, но при прокрутке начинает использоваться экшн в котором я изначально нахожусь. 

Вот код JS в котором я обновляю виджет: 
`$.post( "/category/products", info).done(function( data ) {
        $('#ajaxList').empty();
        //alert(data);
        $('#ajaxList').append(data);
        updateFilter();
    });`

В результате я получаю новый виджет. Возможно костыль, может есть способ обновить только дата-провайдер?

**Comment by kop** [comment]
Hi @sazonov-dev, and sorry for the late response.

Yes, this is possible. ScrollPager is using `Pagination` object from your `$dataProvider`, so after data provider is created, use this technique to change pagination URI:

```php
$dataProvider = new ActiveDataProvider();
$dataProvider->pagination->route = '/category/products';
```

Please see framework docs for details:
http://www.yiiframework.com/doc-2.0/yii-data-pagination.html#$route-detail

**Comment by sazonov-dev** [comment]
Hi @kop , tnx for ur answer
