### ISSUE TITLE
Does not work in tabs

### ISSUE THREAD

**Issue by whmemon** [kop/yii2-scroll-pager#61]
Firstly, I must appreciate efforts to make this extension.  

I am using it with TabsX. getting problem with TabsX because it does not loads separate for each tab. 

the spinner and "load more items" and "You reached the end" are printed on 1st tab only.

**Comment by kop** [comment]
@whmemon, do you mean you have different list views in different tabs?

**Comment by whmemon** [comment]
yes exactly.

--
Waseem Hassan

**Comment by kop** [comment]
@whmemon, see #20. It's not possible to use multiple pager instances on the same page for now.
