### ISSUE TITLE
Does not work on hosting

### ISSUE THREAD

**Issue by TsarS** [kop/yii2-scroll-pager#62]
I'm using

    `<?php
          echo ListView::widget([
        'dataProvider' => $dataProvider,
        'itemOptions' => ['class' => '.item'],
        'itemView' => '_item_view',
        'pager' => ['class' => ScrollPager::className(),
            'enabledExtensions' => [
                ScrollPager::EXTENSION_TRIGGER => 1000,
                ScrollPager::EXTENSION_PAGING,
                ScrollPager::EXTENSION_NONE_LEFT,
                ScrollPager::EXTENSION_SPINNER],
            'spinnerTemplate' => '<div class="ias-spinner" style="text-align: center; z-index:100; "><img src="{src}"/></div>',
            'noneLeftText' => ''
        ],
    ]);
    ?>`
And it works fine on my local server, but when i pull it from bitbacket it shows an error http://example.com/web/site/index?page=2&per-page=6 404 (Not Found) I have the same configuration on local machine and vps (.htacces) and in config file

      'urlManager' => [
             'class' => 'yii\web\UrlManager',
        'showScriptName' => false,
        'enablePrettyUrl' => true,
        'rules' => array(
            '<controller:\w+>/<id:\d+>' => '<controller>/view',
            '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
            '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
        ),
    ],

**Comment by kop** [comment]
Hi @TsarS.

I strongly believe that our issue is not related to this extension and is related to your app configuration.
If Yii says `http://example.com/web/site/index?page=2&per-page=6` not found, it's something wrong with URL manager.
